#!/usr/bin/env python3
"""Form-fill telemetry from *real* browser automation, not from our imagination.

The fraudulent half of Detector 6's training data has to come from somewhere,
and the tempting shortcut - write a function that emits "bot-looking" timings -
is worthless. It would teach the model to separate our human generator from our
bot generator, which we already know how to do, having written both. This
repository has published that mistake twice and is not going to publish it a
third time on its flagship detector.

So the bot side is generated by driving a real headless Chromium against a real
form with the *real* collector on it - `frontend/lib/telemetry.ts`, compiled,
not reimplemented - using the automation APIs a fraud kit actually uses. Whatever
timing artifacts Playwright and the Chrome DevTools Protocol leave behind are
then in the corpus because they are really there, not because we predicted them.

The strategies span the market deliberately, from the lazy end to an attacker who
has read this README:

  * `fill_value`      - set `input.value` directly. No key events at all. This is
                        the majority of kits, and Detector 6 sees an empty buffer.
  * `type_no_delay`   - `locator.type(delay=0)`: CDP key events as fast as the
                        protocol will carry them.
  * `type_fixed`      - a constant inter-key delay. The naive "look human" fix.
  * `type_jitter`     - uniform random delay in a band. The next fix up.
  * `type_gaussian`   - normally distributed delays with a plausible mean and
                        spread, plus occasional pauses. This is a competent
                        attacker who has thought about it, and it is in the
                        corpus specifically so the evaluation cannot claim a win
                        it did not earn.
  * `cdp_raw`         - `Input.dispatchKeyEvent` straight down the protocol,
                        which is what a kit written against CDP rather than
                        Playwright produces.
  * `replay_human`    - the strongest adversary we can build, and the reason the
                        evaluation is worth reading. It takes a *real* typing
                        session out of the Aalto corpus and replays its exact
                        dwell and flight timings through CDP, including the
                        rollover that every other strategy above is physically
                        unable to produce (keyDown for the next key is dispatched
                        before keyUp for the current one). Nothing about its
                        keystroke rhythm is synthetic - it is a real human's
                        rhythm, wearing a bot. If the detector still separates it,
                        that is a finding. If it does not, that is a bigger one,
                        and it belongs in the README either way.

Usage:
    python backend/scripts/bot_telemetry.py --sessions 400 --out datasets/keystrokes/bot_sessions.jsonl
"""
from __future__ import annotations

import argparse
import asyncio
import json
import logging
import random
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "backend"))

log = logging.getLogger("bot_telemetry")

COLLECTOR_TS = REPO / "frontend" / "lib" / "telemetry.ts"
TSC = REPO / "frontend" / "node_modules" / ".bin" / "tsc"

#: The fields a KYC form asks for, in DOM order, with realistic values. `data-tele-field`
#: is what the collector keys its focus and paste events on.
FIELDS = [
    ("name", "Ramesh Kumar Iyer"),
    ("pan", "ABCPK1234F"),
    ("dob", "1988-04-17"),
    ("address", "402 Sunrise Apartments, Andheri East, Mumbai 400069"),
    ("email", "ramesh.iyer@example.com"),
]

PAGE = """<!doctype html><html><body>
<form id="kyc">
%s
</form>
<script>%s</script>
<script>
  window.__collector = new exports.TelemetryCollector();
  window.__collector.start();
</script>
</body></html>"""

FIELD_HTML = '<div data-tele-field="{f}"><label>{f}</label><input id="{f}" name="{f}" /></div>'


def compile_collector() -> str:
    """Compile the shipped collector to JS. Never a reimplementation of it.

    If this file and `telemetry.ts` ever diverge, the bot corpus stops describing
    what production actually records, so it is compiled fresh on every run rather
    than vendored.
    """
    if not TSC.exists():
        raise SystemExit(
            f"tsc not found at {TSC} - run `npm install` in frontend/ first; the bot corpus "
            "is generated through the real collector and will not fall back to a copy of it"
        )
    out = REPO / "storage" / "tmp_collector"
    out.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [str(TSC), str(COLLECTOR_TS), "--target", "es2020", "--module", "commonjs", "--outDir", str(out)],
        capture_output=True, text=True, cwd=REPO / "frontend",
    )
    js = out / "telemetry.js"
    if not js.exists():
        raise SystemExit("tsc produced no telemetry.js")
    # The compiled module is CommonJS; give it the `exports` object it expects.
    return "var exports = {};\n" + js.read_text()


def page_html(collector_js: str) -> str:
    fields = "\n".join(FIELD_HTML.format(f=f) for f, _ in FIELDS)
    return PAGE % (fields, collector_js)


# --------------------------------------------------------------------------- #
# Strategies. Each drives one full form fill and leaves the collector's buffer
# behind for `snapshot()` to return.
# --------------------------------------------------------------------------- #

async def _straight_mouse(page, r: random.Random, steps: int = 0) -> None:
    """Pointer motion the way automation produces it: A to B, optionally in
    equal steps. Playwright's `steps=` argument interpolates *linearly*, which
    is exactly the straight-line path the detector looks for."""
    x, y = r.randint(50, 200), r.randint(50, 200)
    await page.mouse.move(x, y)
    for _ in range(r.randint(2, 5)):
        x, y = r.randint(100, 900), r.randint(100, 600)
        await page.mouse.move(x, y, steps=steps or r.choice([1, 2, 10]))


async def strat_fill_value(page, r):
    for f, v in FIELDS:
        await page.eval_on_selector(f"#{f}", "(el, v) => { el.focus(); el.value = v; }", v)
    await _straight_mouse(page, r)


async def strat_type_no_delay(page, r):
    for f, v in FIELDS:
        await page.click(f"#{f}")
        await page.locator(f"#{f}").type(v, delay=0)
    await _straight_mouse(page, r)


async def strat_type_fixed(page, r):
    delay = r.choice([40, 60, 80, 100, 120])
    for f, v in FIELDS:
        await page.click(f"#{f}")
        await page.locator(f"#{f}").type(v, delay=delay)
    await _straight_mouse(page, r)


async def strat_type_jitter(page, r):
    lo, hi = r.choice([(30, 90), (50, 150), (70, 200)])
    for f, v in FIELDS:
        await page.click(f"#{f}")
        for ch in v:
            await page.keyboard.type(ch, delay=r.randint(lo, hi))
    await _straight_mouse(page, r)


async def strat_type_gaussian(page, r):
    """The competent attacker: gaussian delays, occasional pauses between fields."""
    mu, sigma = r.choice([(120, 40), (150, 55), (95, 30)])
    for f, v in FIELDS:
        await page.click(f"#{f}")
        for ch in v:
            await page.keyboard.type(ch, delay=max(8, int(r.gauss(mu, sigma))))
        await page.wait_for_timeout(max(50, int(r.gauss(700, 300))))
    await _straight_mouse(page, r, steps=r.randint(8, 20))


#: Real human sessions, loaded once, for `replay_human` to replay. Populated by
#: `load_replay_pool`; empty means the strategy is skipped rather than silently
#: degrading into another synthetic one.
_REPLAY_POOL: List[dict] = []


def load_replay_pool(path: Path, limit: int = 400) -> int:
    """Real typing sessions for the replay attacker to wear."""
    _REPLAY_POOL.clear()
    if not path.exists():
        return 0
    with path.open() as fh:
        for i, line in enumerate(fh):
            if i >= limit:
                break
            try:
                _REPLAY_POOL.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return len(_REPLAY_POOL)


async def strat_replay_human(page, r):
    """Replay a real person's dwell and flight through CDP, rollover included.

    This is the attack the whole evaluation hinges on, so it is built to actually
    work rather than to be beatable: timings come from the Aalto corpus, and
    overlapping presses are dispatched in the right order to reproduce negative
    flight, which is the single strongest human signal in the feature set.
    """
    if not _REPLAY_POOL:
        raise RuntimeError("replay pool empty - build the human corpus first")
    session = r.choice(_REPLAY_POOL)
    dwells = [d for d in session["dwells"] if 10 <= d <= 400]
    flights = [f for f in session["flights"] if -120 <= f <= 600]
    if len(dwells) < 20 or len(flights) < 20:
        raise RuntimeError("replay session too short")

    cdp = await page.context.new_cdp_session(page)
    k = 0
    for f, v in FIELDS:
        await page.click(f"#{f}")

        # Lay the presses and releases out on a timeline first, then dispatch in
        # time order. Emitting them inline cannot produce rollover: the release
        # of the current key is always sent before the next key's press, whatever
        # the delays in between, so flight can never go negative. Sorting by
        # timestamp is what lets key i+1 go down while key i is still held.
        events: List[Tuple[float, str, str]] = []
        t = 0.0
        for ch in v:
            dwell = dwells[k % len(dwells)]
            flight = flights[k % len(flights)]
            k += 1
            up = t + dwell
            events.append((t, "keyDown", ch))
            events.append((up, "keyUp", ch))
            t = up + flight  # negative flight puts the next press before this release
        events.sort(key=lambda e: e[0])

        prev = 0.0
        for when, kind, ch in events:
            gap = when - prev
            if gap >= 1.0:
                await page.wait_for_timeout(int(gap))
            prev = when
            payload = {"type": kind, "key": ch}
            if kind == "keyDown":
                payload["text"] = ch
            await cdp.send("Input.dispatchKeyEvent", payload)
    await _straight_mouse(page, r, steps=r.randint(10, 25))


async def strat_cdp_raw(page, r):
    """Straight down the DevTools protocol, the way a non-Playwright kit works."""
    cdp = await page.context.new_cdp_session(page)
    for f, v in FIELDS:
        await page.click(f"#{f}")
        for ch in v:
            await cdp.send("Input.dispatchKeyEvent", {"type": "keyDown", "text": ch, "key": ch})
            await cdp.send("Input.dispatchKeyEvent", {"type": "keyUp", "key": ch})
            await page.wait_for_timeout(r.randint(0, 25))
    await _straight_mouse(page, r)


STRATEGIES = {
    "fill_value": strat_fill_value,
    "type_no_delay": strat_type_no_delay,
    "type_fixed": strat_type_fixed,
    "type_jitter": strat_type_jitter,
    "type_gaussian": strat_type_gaussian,
    "cdp_raw": strat_cdp_raw,
    "replay_human": strat_replay_human,
}


async def _one_session(browser, html: str, name: str, seed: int) -> Optional[dict]:
    """Drive one fill in its own context, so nothing leaks between sessions."""
    r = random.Random(seed)
    ctx = await browser.new_context(
        viewport={"width": r.choice([1280, 1366, 1920]), "height": r.choice([720, 768, 1080])},
        locale=r.choice(["en-US", "en-IN", "ru-RU", "en-GB"]),
    )
    page = await ctx.new_page()
    try:
        await page.set_content(html)
        await STRATEGIES[name](page, r)
        # A kit that pads with a sleep before submitting is common enough to be
        # worth having in the corpus at a realistic rate.
        if r.random() < 0.25:
            await page.wait_for_timeout(r.choice([300, 500, 1000]))
        buf = await page.evaluate("() => window.__collector.snapshot('bot','IN')")
        buf.update(strategy=name, label=1, subject=f"bot::{name}")
        return buf
    except Exception as exc:  # noqa: BLE001
        log.warning("session %d (%s) failed: %s", seed, name, exc)
        return None
    finally:
        await ctx.close()


async def collect(sessions: int, out_path: Path, headless: bool = True,
                  concurrency: int = 4) -> Dict[str, int]:
    """Generate the bot corpus, writing incrementally.

    Appended session by session rather than held in memory and dumped at the end:
    the replay attacker replays real human timings in real time, so a full corpus
    is hours of wall clock, and a run that loses everything on an interruption at
    hour three is not worth starting.
    """
    from playwright.async_api import async_playwright

    html = page_html(compile_collector())
    counts: Dict[str, int] = {k: 0 for k in STRATEGIES}
    names = list(STRATEGIES)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    done = 0
    sem = asyncio.Semaphore(concurrency)
    lock = asyncio.Lock()

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=headless)
        fh = out_path.open("a")

        async def run(i: int) -> None:
            nonlocal done
            name = names[i % len(names)]
            async with sem:
                buf = await _one_session(browser, html, name, i)
            async with lock:
                if buf is not None:
                    fh.write(json.dumps(buf) + "\n")
                    fh.flush()
                    counts[name] += 1
                done += 1
                if done % 25 == 0:
                    log.info("%d/%d sessions", done, sessions)

        await asyncio.gather(*(run(i) for i in range(sessions)))
        fh.close()
        await browser.close()
    return counts


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sessions", type=int, default=600)
    ap.add_argument("--out", type=Path, default=REPO / "datasets/keystrokes/bot_sessions.jsonl")
    ap.add_argument("--headed", action="store_true", help="watch it drive the form")
    ap.add_argument("--concurrency", type=int, default=4)
    ap.add_argument("--replay-pool", type=Path,
                    default=REPO / "datasets/keystrokes/human_aalto.jsonl",
                    help="real sessions for the replay attacker to wear")
    args = ap.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    n = load_replay_pool(args.replay_pool)
    if n:
        log.info("replay attacker loaded %d real human sessions to wear", n)
    else:
        log.warning("no replay pool at %s - the strongest adversary will be MISSING from "
                    "the corpus, and any AUC from it will be an overstatement", args.replay_pool)
    counts = asyncio.run(collect(args.sessions, args.out, headless=not args.headed,
                                concurrency=args.concurrency))
    total = sum(counts.values())
    log.info("wrote %d sessions to %s", total, args.out)
    for k, v in sorted(counts.items()):
        log.info("  %-16s %4d", k, v)


if __name__ == "__main__":
    main()
